### PR TITLE
Added support for Decimal

### LINKED ISSUE #28: Add decimal to the possible numbers?
Decimal is different from double and float in that it supports base 10 numbers much better that double and float do. I would love for decimal to be supported by node natively.

### PR DESCRIPTION
**Pull request by Evertt**
Fixes #28

### CODE REVIEW

**Comment by Evertt** [comment]
Hmm strange, the tests worked for me locally without import foundation. I'll see if importing foundation works to fix the tests.

**Comment by loganwright** [comment]
@Evertt thanks for the PR, but unfortunately we won't be able to merge this now for a few reasons, including a breaking api change. The biggest issue though is that decimal number appears to be unimplemented in Foundation for Linux, so it seems like it's just not capable to be supported at the moment either way.

Let me know if you come up with a way around this and we can revisit the other stuff including the breaking api.

Best,

Logan

**Comment by Evertt** [comment]
Unfortunately I don't directly know a way around this. Like maybe NSDecimalNumber would be supported, but I'd rather wait for the Swift Decimal type to be supported on linux. So let's come back to this at another time.

**Comment by loganwright** [comment]
@Evertt awesome, I'm gonna mark it closed, reopen it and we'll reevaluate :)

**Pull request closed without merging**
