### PR TITLE
Make Data NodeConvertible

### PR DESCRIPTION
**Pull request by Chylis**

### CODE REVIEW

**Comment by loganwright** [comment]
@Chylis the reasoning behind not doing this previously was because some people (me in particular ;) ) might want to map their data as JSON to a full Node object.

I'm happy to be overruled on this, but would like to gather some opinions on it before going through. If that happens, let's throw on a few quick tests and get it merged. As of now, I'd prefer to keep data out of the official library and let people add their own extensions.

Thanks for contributing to the Vapor community, we really appreciate it, and I look forward to some discussions on this thread. 

For reference, this is my preferred implementation: https://github.com/LoganWright/Genome/blob/master/Sources/GenomeFoundation/Foundation.swift#L5
Which by implementing this here would break that lib.

**Comment by sroebert** [comment]
@LoganWright I understand the issue and can imagine this can happen for converting any non-supported `Node` type to a `Node`. Even though, this addition could be nice, it might be better to leave these kind of implementations to projects using them, as each project could have a different interpretation of the conversions. You have a good example with Genome.

Another option could be to simply rename your method. But then again, if the type is not directly represented by `Node`, who decides which is the right way to convert another type into a `Node`.

**Comment by Chylis** [comment]
@LoganWright Thanks for the explanation (together with the Genome example). I can see the benefits of leaving it to the implementing projects. Feel free to close this PR :-)

**Comment by loganwright** [comment]
@Chylis sounds good to me, thanks so much for participating in Vapor! I'm looking forward to more future contributions.

**Pull request closed without merging**
